language: go
go: 
 - 1.7.1
 - tip

env:
  global:
    - CC=gcc-4.8
    - CXX=g++-4.8
    - export PATH="$PATH:$HOME/bin"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
 - make capnproto

script:
 - make build
 - make test
